### ISSUE TITLE
Unclear installation instructions

### ISSUE THREAD

**Issue by powerllama** [vinavfx/ComfyUI-for-Nuke#14]
In step 2 you list:

```
# Since nuke cannot install external packages, websocket must be installed 
# in system Python and then included in nuke !

# The version of python where websocket will be installed
# has to be the same as the python version of nuke !

pip install websocket-client
```

To make this more clear, perhaps this could be changed to something like:

```
# Since nuke cannot install external packages, websocket must be installed 
# in system Python and then included in nuke !

# The version of python where websocket will be installed
# has to be the same as the python version of nuke !
# For example, Nuke 14/15 use Python 3.10

python3.10 -m pip install websocket-client
```

This will run pip as a submodule of python 3.10 specifically, so it will get installed to the proper version of Python that aligns with Nuke's Python version.

(sorry for the accidental double post) Submitted this as an issue, but could also fork and make a pull request.

**Comment by vinavfx** [comment]
It is clear that websocket cannot be installed directly on Nuke, so the Python library of the operating system must be imported, and for that reason that version of the system must be the same as that of Nuke because different versions will not be compatible.
![Screenshot at 2024-09-07 22-44-38](https://github.com/user-attachments/assets/0011229e-73d3-46e0-84ad-3b33b5097006)

**Comment by vinavfx** [comment]
You are right, so I updated point 2.
https://github.com/vinavfx/ComfyUI-for-Nuke/commit/588d60c9e4086b54b832b945778423912f4109f0

thanks

**Comment by powerllama** [comment]
I think it’s important to do the python import specific way of installing the module so it’s installed in the same python version that is compatible with Nike’s version. So when you install with `python3.10 -m pip install` it will install the correct version into the correct python version.

**Comment by vinavfx** [comment]
https://github.com/vinavfx/ComfyUI-for-Nuke/commit/c074a0b54f0ece521fac2a913404e66b4d541c10

**Comment by powerllama** [comment]
Thanks!
