### ISSUE TITLE
Animating knobs

### ISSUE THREAD

**Issue by claussteinmassl** [vinavfx/ComfyUI-for-Nuke#21]
Hey, 
thanks a lot for this awesome project!
I'm trying to animate some knobs of ComfyUI nodes, but the animation isn't applied. I guess this is due to the fact, that the workflow is just send once and only the first value of the node is send to ComfyUI, which then just processes the entire batch of images with this one value.
I'm not sure about the best way to tackle this. Maybe there could be another button on the QueuePrompt node, which queues the workflow for each incoming frame from the given frame range individually, but saves the files as one sequence. Or maybe there is an even smarter way to manipulate the values based on the currently processed batch or image list frame? What do you think?

Thanks in advance!
Cheers,
Claus

**Comment by vinavfx** [comment]
It can be animated in ComfyUI ?, I've only seen lists of keyframes to perform different actions depending on the frame.
I imagine that you could transfer those nuke keyframes to a list, but I really don't know.
![keyframes_01](https://github.com/user-attachments/assets/73c7e4ab-3614-4ed5-86dd-68d79da4a681)

**Comment by vinavfx** [comment]
https://github.com/melMass/comfy_mtb/wiki/nodes-animation-builder

**Comment by vinavfx** [comment]
I liked your idea and finally implemented it, tell me how it goes.
https://github.com/vinavfx/ComfyUI-for-Nuke/commit/f150f2e50387cc51302e6da1e69e07111dc96ed3

**Comment by claussteinmassl** [comment]
Thanks for your super fast response and implementation! 
Unfortunately it's not working for me, yet. Here are some observations I made:

- Once I Submit I get a prompt for a frame range (which defaults to the comp range, in my case 1001 - 1055). I chose a shorter range for testing (1011 - 1045), but this was ignored. The whole sequence got send to comfy (rendered out of Nuke and processed).
- Comfy's log showed only once "got prompt". I would have assumed to see this for every single frame if they are queued independently, right?
- Comfy processed 55 images and saved 55 images, but the entire resulting sequence is just the last frame of my sequence (for both the image itself and also the animation value, that was used).
- The read node is not created after completion. There are no errors in the shell, but the sequence is not loaded automatically into Nuke as before.
- I am using "Image Batch to Image List" as a first step in my setup, as the nodes I am using for processing aren't able to process a batch of images, so I am processing them one by one, which is slower, but at least works. Could this be an issue with the current implementation? If I disable this node, just the first frame is processed (but the read node get's created in this case!)

I will try to investigate this further. Hope this helps you for debugging, too. Let me know if you need any other information.

Thanks a lot!

**Comment by vinavfx** [comment]
I have corrected several things, at the moment it is working if all input batches are 1

**Comment by vinavfx** [comment]
What I am not able to resolve is that if there is an input sequence it remains with a batch greater than 1, and that would be sending the entire range for each frame, eg: if my sequence has a range of 1-10, for each request I would be sending frame1: 1-10, frame2: 1-10, frame3: 1-10, etc.

**Comment by claussteinmassl** [comment]
I couldn't test it, yet, but could it help to set the image_load_cap to 1 and skip_first_images to the corresponding index if we are submitting animation?

https://github.com/vinavfx/ComfyUI-for-Nuke/blob/5b40eef0affbdf41702f6f52a68d53df3f31fa99/src/nodes.py#L108-L110

**Comment by claussteinmassl** [comment]
I just wanted to try the latest version, but I can't submit anything anymore as something seems to have changed with the handling of enumeration knobs.

In the Comfy Shell I can see this:
```
Failed to validate prompt for output SaveEXR2:
* (prompt):
  - Value not in list: save_workflow: '3' not in ['ui', 'api', 'ui + api', 'none']
* ExpressionEditor ExpressionEditorPHM2:
  - Value not in list: sample_parts: '0' not in ['OnlyExpression', 'OnlyRotation', 'OnlyMouth', 'OnlyEyes', 'All']
* SaveEXR SaveEXR2:
  - Value not in list: save_workflow: '3' not in ['ui', 'api', 'ui + api', 'none']
Output will be ignored
Failed to validate prompt for output ExpressionEditorPHM2:
* (prompt):
  - Value not in list: sample_parts: '0' not in ['OnlyExpression', 'OnlyRotation', 'OnlyMouth', 'OnlyEyes', 'All']
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': "Value not in list: save_workflow: '3' not in ['ui', 'api', 'ui + api', 'none']\nValue not in list: sample_parts: '0' not in ['OnlyExpression', 'OnlyRotation', 'OnlyMouth', 'OnlyEyes', 'All']", 'extra_info': {}}
```

Seems as Nuke is sending indexes instead of the actual value, right?

**Comment by vinavfx** [comment]
Can you send me a .nk with the minimum nodes so that I get that error, please?

**Comment by vinavfx** [comment]
I already got the error, since I was using SaveImage and the error only appears in SaveExr

**Comment by claussteinmassl** [comment]
I figured out why this is happening. It's due this:

https://github.com/vinavfx/ComfyUI-for-Nuke/blob/5b40eef0affbdf41702f6f52a68d53df3f31fa99/src/nodes.py#L244-L253

hasattr(knob, 'valueAt') returns True and valueAt on the EnumerationKnob return the index, while value returns the actual string, that we are interested in. I think we must adjust this, so the check for enumeration knobs comes first and the valueAt is not executed on those knobs.

```
print(hasattr(knob, 'valueAt'))
# Result: True

print(knob.valueAt(1001))
# Result: 0.0
```

I will prepare a little Nuke File in the meanwhile.

**Comment by claussteinmassl** [comment]
[nuke_comfy_animation.nk.zip](https://github.com/user-attachments/files/17077913/nuke_comfy_animation.nk.zip)

Here is a minimalistic example file. The comfy node is from AdvancedLivePortrait:
https://github.com/PowerHouseMan/ComfyUI-AdvancedLivePortrait

**Comment by vinavfx** [comment]
Done, the last thing is solved
https://github.com/vinavfx/ComfyUI-for-Nuke/commit/5ae7cdac3f134c45e07479ce07f6869bb237f275

**Comment by vinavfx** [comment]
I already tried your script and it works perfectly with an image, now we have to solve it in sequence

![anim](https://github.com/user-attachments/assets/eae0a963-339f-44fb-bbfd-ca26bbe2dad6)

**Comment by claussteinmassl** [comment]
I just checked the latest version. With the fix I can submit again, but there is still something not right with the frame range being send: It still sends 55 frames to Comfy, even though I only select my range without handles (1011-1045).
When I send the sequence comfy process frame 1001 for the whole sequence (so the resulting sequence is a still image), but applies the animation correctly. It's also very slow, as each iteration is loading all 55 frames in Comfy.

What do you think about my comment from before to limit the loader with image_load_cap to 1 and skip_first_images to only the needed frame? I think this should speed things up and process the correct image for each frame.

**Comment by vinavfx** [comment]
The range works fine for me, and also when I change it, I don't know what's happening.

**Comment by vinavfx** [comment]
I made a mistake and put report, and what you wrote was deleted.

Yes, I understand you about this "image_load_cap to 1 and skip_first_images", but I still don't see it, the problem is in the sequence that is rendered to send, but I will see it there

**Comment by claussteinmassl** [comment]
> I tested it with a photo, you can confirm if it works for you with a photo

If I just plugin a photo it works. The animation is correctly applied.
If I add a FrameRange node after the photo (to simulate a sequence), the entire range of 55 frames is processed for each iteration, so 55 * 55 frames are processed.

**Comment by vinavfx** [comment]
That's what I wanted to know, I haven't gotten into the other stuff yet.

**Comment by vinavfx** [comment]
Ready, the animation for sequences is working, but it will be incompatible for the moment with the state, every time it is sent to ComfyUI each frame will be rendered in nuke, but for me for the moment it is fine,

You just have to confirm if it works for you and if there is any error to close the issue.

This is very interesting to make a video
and thanks for the help.

https://github.com/vinavfx/ComfyUI-for-Nuke/commit/d54e77c3a48561937eda69f74fe55c96c56e9f49

**Comment by vinavfx** [comment]
![anim](https://github.com/user-attachments/assets/4c7c51fc-312f-4016-8c48-718bd707a23f)

**Comment by claussteinmassl** [comment]
Yes, I conform it's working now!
Thanks so much for very fast response and your effort to implement this feature!

**Comment by vinavfx** [comment]
With more time I'll see how to make it work better, so that it is sent in batches and not frame by frame, which is slower.
