### ISSUE TITLE
TCL Expression in nodes

### ISSUE THREAD

**Issue by IIWstudio** [vinavfx/ComfyUI-for-Nuke#25]
Hello, 

Was wondering if there was any way to enhanced the Queue Prompt node with the ability to resolve TCL expression in Write EXR Frame for exemple. I would like the filepath_ to be nicely integreted in my pipeline but i did not managed to find a solution. 

I have tried this script in the submit button of the Queue Prompt : 

```
import nuke

node = nuke.toNode('SaveEXRFrames')
knob = node['filepath_']

original_expression = knob.toScript()

evaluated_value = knob.evaluate()

knob.setValue(evaluated_value)

comfyui.queue_prompt.comfyui_submit()

knob.fromScript(original_expression)
```
But ComfyUI is still flaging the fact that the path is not ending with .exr ou .EXR 

Thank you for your hard work, this project is amazing !

**Comment by vinavfx** [comment]
in that line I am modifying the filepath_ to convert the '####' to '%04d' since the # are not compatible in the SaveExr, but you are not putting either of the 2, you have 2 options: return the function  before so that it does not take effect or what you send yes or yes you have to pass the #### or the %04d it cannot go like this 0001.
At least in SaveEXRFrames, or you have to use SaveEXR and go look for the output files, tell me if it works without the range signs to correct it
![image](https://github.com/user-attachments/assets/4ada0cdf-4fc3-4149-8fcc-3b601a159822)

**Comment by vinavfx** [comment]
and they also have to be 4 digits

https://github.com/spacepxl/ComfyUI-HQ-Image-Save
![image](https://github.com/user-attachments/assets/3feab8b4-05ca-4fd3-ae7c-18d012cfd860)

**Comment by vinavfx** [comment]
This had problems and I solved it there, let me know if it works for you.
https://github.com/vinavfx/ComfyUI-for-Nuke/commit/a3ab6521ebcb67d3002c7c9c53e403e8abe220b4

**Comment by IIWstudio** [comment]
Oh i see, the evaluation of the tcl was returning frame number instead of ####. 

```
import nuke
import re

node = nuke.toNode('SaveEXRFrames_AutoRestore')
knob = node['filepath_']

original_expression = knob.toScript()

evaluated_value = knob.evaluate()

knob.setValue(evaluated_value)

pattern = r'(\d{4})(?=\.exr$)'
final_expression = re.sub(pattern, '%04d', evaluated_value)
knob.setValue (final_expression)
print (final_expression)

comfyui.queue_prompt.comfyui_submit()
print (original_expression)
knob.fromScript(original_expression)
```

This is working for me :)

**Comment by vinavfx** [comment]
is everything ok to close this?

**Comment by IIWstudio** [comment]
Yes thank you, I let you see if you find intersting to convert tcl expression when queuing the prompt !

**Comment by vinavfx** [comment]
All knob get the value, or get the value by calculating the expression, except for text knob, and I see that is your case, but as soon as I have more time I will check if it is necessary to implement it.

**Comment by vinavfx** [comment]
That's where the value of the knob is extracted, if you want you can implement them and make me a pull request.
![image](https://github.com/user-attachments/assets/487215a6-6c29-4f60-a09c-1064f7f8c034)

**Comment by vinavfx** [comment]
Will you implement it or close this issue?

**Comment by vinavfx** [comment]
I'm closing this because there is no response.
