### ISSUE TITLE
Directory "<ComfyUI>" does not exist 

### ISSUE THREAD

**Issue by IvayloPask** [vinavfx/ComfyUI-for-Nuke#26]
Hi , 
I install everything and all my tools and custom nodes from ComfyUi is visible in my Nuke 15.0v1 , but :

Directory "<ComfyUI>" does not exist 

Then I try to work , this message stop me !

Thanks

**Comment by vinavfx** [comment]
read the instructions at the end of env.py...

**Comment by IvayloPask** [comment]
<img width="1065" alt="Screenshot 2024-09-28 230910" src="https://github.com/user-attachments/assets/7b278c2b-a913-4002-8871-db9bda83fd75">
<img width="1013" alt="Screenshot 2024-09-28 230937" src="https://github.com/user-attachments/assets/83f773d4-750b-4a49-b575-2d66e59a5034">
<img width="928" alt="Screenshot 2024-09-28 231008" src="https://github.com/user-attachments/assets/0110f1c7-0c47-4991-8f30-bb8ceb3ba93d">

**Comment by vinavfx** [comment]
You are putting '<>' in the path, those signs are just to indicate that it is a path

**Comment by IvayloPask** [comment]
Thanks a lot, I'll definitely have to put some effort into learning Python!
