### ISSUE TITLE
Directory "<ComfyUI>" does not exist

### ISSUE THREAD

**Issue by waltonhk** [vinavfx/ComfyUI-for-Nuke#27]
![Screenshot 2024-09-30 185222](https://github.com/user-attachments/assets/c66ad245-2046-4fc0-a4a4-67f25015cfab)

I have connected Queue Prompt, sorry I am new to  ComfyUI.

**Comment by vinavfx** [comment]
https://github.com/vinavfx/ComfyUI-for-Nuke/issues/26
