### ISSUE TITLE
Queue Prompt not connected

### ISSUE THREAD

**Issue by waltonhk** [vinavfx/ComfyUI-for-Nuke#28]
I have connected Queue Prompt, sorry I am new to ComfyUI.
![Screenshot 2024-09-30 185222](https://github.com/user-attachments/assets/696d106d-b237-42e6-97d3-380b33fe3530)

**Comment by vinavfx** [comment]
Send me the .nk script to review it

**Comment by waltonhk** [comment]
I am using Nuke Indle will that be the problem? 
![Screenshot 2024-09-30 194525](https://github.com/user-attachments/assets/64780a8d-2ec5-4131-9225-19e5e4375445)

https://drive.google.com/file/d/1OU0j3guP71iV12J-NqI766Cgafn7V8FR/view?usp=drive_link

**Comment by vinavfx** [comment]
It won't let me open your script because it's not .nk, tomorrow I'll do a test on Windows with nuke 15.1 and if it works it must be a problem with the indie

**Comment by waltonhk** [comment]
Thank you so much for your quick response

**Comment by vinavfx** [comment]
If you have the possibility to test it on a normal nuke weapon, to remove the doubt

**Comment by waltonhk** [comment]
ok, I tried using Nuke and recreated the script, it works on Nuke.

**Comment by vinavfx** [comment]
I tried it on Windows and Nuke version 15.1 and it works, so the problem must be the indie version of Nuke.

**Comment by waltonhk** [comment]
Thank you for being so helpful
