### ISSUE TITLE
Menu.py: Error intepreting this plugin

### ISSUE THREAD

**Issue by paboman** [vinavfx/ComfyUI-for-Nuke#29]
Nuke 14.1v4
Python 3.11.9
ComfyUI up and running

Installed websocket client with: `pip install websocket-client`

![nuke 4](https://github.com/user-attachments/assets/c4c1cdf2-c2d6-43e5-a4b6-9c55e0e00aae)

After creating menu.py in `C:\Users\<user>\.nuke` I get an error when launching Nuke 14.1v4

![nuke 1](https://github.com/user-attachments/assets/73cc3389-7330-40f6-a8ba-68864b9963f2)

menu.py:
![nuke 2](https://github.com/user-attachments/assets/a7f088bc-41dc-4e2e-9508-d776d3150337)

Nuke console:
![nuke 3](https://github.com/user-attachments/assets/3db57ba2-465c-46b2-b26c-7fcd7d69cdef)

What am I doing wrong ?

**Comment by vinavfx** [comment]
change the slashes from \ to /

**Comment by paboman** [comment]
> change the slashes from \ to /



changed slashes from \ to / but I get the same error on Nuke launch: Error intepreting this plugin
ComfyUI up and running
![nuke slashes](https://github.com/user-attachments/assets/009624f8-996e-4b88-a9cb-2d140ed25167)

![nuke 6](https://github.com/user-attachments/assets/69ca5f0d-940d-4c7c-882f-7a1e96d63670)


Can this be related to the fact I have no models yet installed ?

**Comment by vinavfx** [comment]
It is not the same error, and if the slashes were wrong, the new error is because you do not have the websocket installed

**Comment by paboman** [comment]
> It is not the same error, and if the slashes were wrong, the new error is because you do not have the websocket installed

I have installed websocket with the option A: Direct Installation (System-Wide) using `pip install websocket-client`

![nuke 7](https://github.com/user-attachments/assets/53e57841-4ec5-4b74-8028-0b7c6e9240a5)

**Comment by vinavfx** [comment]
maybe it's because the python version of nuke 14.1 is older the python version is 3.9.10

**Comment by paboman** [comment]
> maybe it's because the python version of nuke 14.1 is older the python version is 3.9.10

what do you suggest to do ?

**Comment by vinavfx** [comment]
install that one: https://www.python.org/downloads/release/python-3910/
install the websocket in that version
and change the site-package to version 3.9.10

**Comment by vinavfx** [comment]
I'm going to update the README.md, you have to wait, yes, I'll make everything clearer there

**Comment by vinavfx** [comment]
I updated the instructions, in your case it is only necessary to run this in the cmd:
"C:\Program Files\Nuke14.1v4\python.exe" -m pip install websocket-client

and it is not necessary to put the lines of nuke.pluginAddPath(.... since the websocket is inside the nuke directory:

https://github.com/vinavfx/ComfyUI-for-Nuke/commit/707e75fccad5711de7c2ded1e075e3ef93807f18

**Comment by paboman** [comment]
> I updated the instructions, in your case it is only necessary to run this in the cmd: "C:\Program Files\Nuke14.1v4\python.exe" -m pip install websocket-client
> 
> and it is not necessary to put the lines of nuke.pluginAddPath(.... since the websocket is inside the nuke directory:
> 
> [707e75f](https://github.com/vinavfx/ComfyUI-for-Nuke/commit/707e75fccad5711de7c2ded1e075e3ef93807f18)

After your last advice I was able to start Nuke14.1v4 and have the ComfyUI menu icon working !
Many thanks for you patience

Now I am getting:
Cannot import D:\ComfyUI\custom_nodes\ComfyUI-HQ-Image-Save module for custom nodes: No module named 'cv2'
![nuke 8](https://github.com/user-attachments/assets/9b29103b-7e6e-44f6-9692-9aa7df30f46a)
![hq image save 1](https://github.com/user-attachments/assets/3a1a16d4-4b34-491f-b001-836059dcc8da)
![hq image save 2](https://github.com/user-attachments/assets/b95fa56e-df1d-4f68-b66d-64bd7404a327)

**Comment by vinavfx** [comment]
This has nothing to do with this so I'm closing it, there is a .bat inside that plugin, you have to run it for the dependencies to be installed
